# -*- coding: utf-8 -*-

# Create a program that will play the “cows and bulls” game with the user. The
# game works like this:

# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number.
# For every digit that the user guessed correctly in the correct place, they 
# have a “cow”. For every digit the user guessed correctly in the wrong place 
# is a “bull.” Every time the user makes a guess, tell them how many “cows” 
# and “bulls” they have. Once the user guesses the correct number, the game 
# is over. Keep track of the number of guesses the user makes throughout the
# game and tell the user at the end.

# Say the number generated by the computer is 1038. An example interaction
# could look like this:

#   Welcome to the Cows and Bulls Game! 
#   Enter a number: 
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1256
#   1 cow, 1 bull
#   ...

# Until the user guesses the number.

import random

input_number = raw_input("Enter a number: ")

my_num = random.randint(1000, 9999)
splited_my_num = list(str(my_num))
splited_input = list(str(input_number))

i = 0

while i < 4:
	if splited_my_num[i] == splited_input[i]:
		print ("bull")
	i += 1

print (splited_my_num)
print (splited_input)